/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import reports.ReportService;

/**
 *
 * @author brais
 */
public class MainJasper extends javax.swing.JFrame {

    private static final String REPORT_PATH_PLAYERS = "/reports/players.jrxml";
    private static final String REPORT_PATH_INSCRIPTIONS = "/reports/inscriptions.jrxml";

    private final ReportService reportService;

    /**
     * Creates new form MainJasper
     */
    public MainJasper() {
        initComponents();

        setTitle("Jasper Reports");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Properties prop = new Properties();
        try {
            prop.load(MainJasper.class.getClassLoader().getResourceAsStream("config.properties"));
        } catch (IOException ex) {
            ex.printStackTrace();
            this.dispose();
        }

        reportService = new ReportService(
        prop.getProperty("dburl"),
        prop.getProperty("dbuser"),
        prop.getProperty("dbpassword"));

        try {
            Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pelota.png"));
            setIconImage(icon);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSavePlayers = new javax.swing.JButton();
        btnViewPlayers = new javax.swing.JButton();
        btnViewAndSavePlayers = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnViewInscriptions = new javax.swing.JButton();
        btnSaveInscriptions = new javax.swing.JButton();
        btnViewAndSaveInscriptions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Players"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        btnSavePlayers.setText("Save Pdf");
        btnSavePlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlayersActionPerformed(evt);
            }
        });
        jPanel1.add(btnSavePlayers, java.awt.BorderLayout.CENTER);

        btnViewPlayers.setText("View Report");
        btnViewPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPlayersActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewPlayers, java.awt.BorderLayout.PAGE_START);

        btnViewAndSavePlayers.setText("View and Save");
        btnViewAndSavePlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAndSavePlayersActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAndSavePlayers, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Inscriptions"));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new java.awt.BorderLayout());

        btnViewInscriptions.setText("View Report");
        btnViewInscriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInscriptionsActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewInscriptions, java.awt.BorderLayout.PAGE_START);

        btnSaveInscriptions.setText("Save Pdf");
        btnSaveInscriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInscriptionsActionPerformed(evt);
            }
        });
        jPanel2.add(btnSaveInscriptions, java.awt.BorderLayout.CENTER);

        btnViewAndSaveInscriptions.setText("View and Save");
        btnViewAndSaveInscriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAndSaveInscriptionsActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewAndSaveInscriptions, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPlayersActionPerformed
        try {
            reportService.get(REPORT_PATH_PLAYERS).view();
        } catch (Exception ex) {
            Logger.getLogger(MainJasper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewPlayersActionPerformed

    private void btnSavePlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlayersActionPerformed
        SavePdfChooser chooser = new SavePdfChooser(this);
        String dest = chooser.getFilePath();
        try {
            reportService.get(REPORT_PATH_PLAYERS).toPdf(dest, true);
        } catch (Exception ex) {
            Logger.getLogger(MainJasper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSavePlayersActionPerformed

    private void btnViewAndSavePlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAndSavePlayersActionPerformed
        SavePdfChooser chooser = new SavePdfChooser(this);
        String dest = chooser.getFilePath();
        try {
            reportService.get(REPORT_PATH_PLAYERS).view().toPdf(dest, false);
        } catch (Exception ex) {
            Logger.getLogger(MainJasper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewAndSavePlayersActionPerformed

    private void btnViewInscriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInscriptionsActionPerformed
        try {
            reportService.get(REPORT_PATH_INSCRIPTIONS).view();
        } catch (Exception ex) {
            Logger.getLogger(MainJasper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewInscriptionsActionPerformed

    private void btnSaveInscriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInscriptionsActionPerformed
        SavePdfChooser chooser = new SavePdfChooser(this);
        String dest = chooser.getFilePath();
        try {
            reportService.get(REPORT_PATH_INSCRIPTIONS).toPdf(dest, true);
        } catch (Exception ex) {
            Logger.getLogger(MainJasper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveInscriptionsActionPerformed

    private void btnViewAndSaveInscriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAndSaveInscriptionsActionPerformed
        SavePdfChooser chooser = new SavePdfChooser(this);
        String dest = chooser.getFilePath();
        try {
            reportService.get(REPORT_PATH_INSCRIPTIONS).view().toPdf(dest, false);
        } catch (Exception ex) {
            Logger.getLogger(MainJasper.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewAndSaveInscriptionsActionPerformed

 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJasper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainJasper().setVisible(true);
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveInscriptions;
    private javax.swing.JButton btnSavePlayers;
    private javax.swing.JButton btnViewAndSaveInscriptions;
    private javax.swing.JButton btnViewAndSavePlayers;
    private javax.swing.JButton btnViewInscriptions;
    private javax.swing.JButton btnViewPlayers;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
